### ISSUE TITLE
but this code only for multi lines comments not for single lines comment

### ISSUE THREAD

**Issue by ashok1708** [Arjitc12/C-#1]
but this code only for multi lines comments not for single lines comment

**Comment by bhavesh2699** [comment]
this is not using file handling concept??

**Comment by Arjitc12** [comment]
> but this code only for multi lines comments not for single lines comment

It Works f

> but this code only for multi lines comments not for single lines comment

Thank You, Ashok

Now It works for both

**Comment by Arjitc12** [comment]
> this is not using file handling concept??

No I am not writing the uncommented content onto another file I am just printing it over the console.
